import type { ProjectRun } from '../../../shared/multi-ai'
export function MultiAiRun({ run, onRestart, busy }: { run: ProjectRun; onRestart: () => void; busy: boolean }) {
  const complete = run.tasks.filter(task => task.status === 'COMPLETED').length
  return <section className="multi-run" aria-label="ALTREX Director run">
    <header><strong>ALTREX Director</strong><span>{run.status.toLowerCase()}</span></header>
    <p className="metadata">{run.tasks.length ? `${complete} / ${run.tasks.length} tasks verified` : 'Analyzing project and creating task contracts'}</p>
    {!!run.tasks.length && <progress value={complete} max={run.tasks.length} aria-label="Verified tasks" />}
    {run.spec && <details><summary>Master specification</summary><h4>{run.spec.project}</h4><p>{run.spec.goal}</p>{(['stack', 'architecture', 'designRules', 'apiContracts', 'dataModels', 'requirements', 'decisions'] as const).map(key => run.spec![key].length > 0 && <div key={key}><strong>{key.replace(/([A-Z])/g, ' $1')}</strong><ul>{run.spec![key].map((value, index) => <li key={index}>{value}</li>)}</ul></div>)}</details>}
    <div className="specialist-list">{run.tasks.map(task => <details key={task.id} className="specialist-task"><summary><span><strong>{task.title}</strong><small>{task.role} · {task.model ?? 'Awaiting assignment'}</small></span><span className={`task-status task-${task.status.toLowerCase()}`}>{task.status}</span></summary><p>{task.description}</p><dl><dt>Model</dt><dd>{task.provider ? `${task.provider} / ${task.model}` : 'Not assigned'}</dd><dt>Attempt</dt><dd>{task.attempt} / 3</dd><dt>Depends on</dt><dd>{task.dependencies.join(', ') || 'Independent'}</dd><dt>Owns</dt><dd>{task.allowedFiles.join(', ')}</dd><dt>Restricted</dt><dd>{task.restrictedFiles.join(', ') || 'All files outside ownership'}</dd><dt>Changed files</dt><dd>{task.filesChanged.join(', ') || 'None yet'}</dd></dl><strong>Acceptance criteria</strong><ul>{task.acceptance.map((item, i) => <li key={i}>{item}</li>)}</ul>{task.error && <p className="danger">{task.error}</p>}{task.verification && <div><strong>{task.verification.passed ? 'Verification passed' : 'Verification failed'}</strong><p>{task.verification.summary}</p><small>Reviewer: {task.verification.reviewer}</small>{task.verification.commands.map((command, i) => <details key={i}><summary>{command.command} · exit {command.exitCode ?? 'unknown'}</summary><pre className="command-output">{command.output}</pre></details>)}</div>}<details><summary>Actions and results</summary>{task.actions.map((action, i) => <p key={i}>{action}</p>)}{task.result && <p>{task.result}</p>}</details></details>)}</div>
    <details><summary>Director activity · {run.activity.length}</summary>{run.activity.map((action, i) => <p key={i}>{action}</p>)}</details>
    {run.finalVerification && <details><summary>Final QA · {run.finalVerification.passed ? 'passed' : 'failed'}</summary><p>{run.finalVerification.summary}</p>{run.finalVerification.commands.map((command, i) => <details key={i}><summary>{command.command} · exit {command.exitCode ?? 'unknown'}</summary><pre className="command-output">{command.output}</pre></details>)}</details>}
    {run.error && <p className="danger">{run.error}</p>}
    {['FAILED', 'CANCELLED', 'INTERRUPTED'].includes(run.status) && <button className="secondary-button" disabled={busy} onClick={onRestart}>Restart unfinished tasks</button>}
  </section>
}
