import { useState } from 'react'
import { Cpu, KeyRound, Palette, ShieldCheck, X } from 'lucide-react'
import { AltrexLogo } from '../AltrexBrand'
import type { AltrexController } from '../useAltrex'
import { Dialog, IconButton, Toggle } from './primitives'
import { MultiAiRun } from './MultiAiRun'

export function SettingsDialog({ app }: { app: AltrexController }) {
  const [tab, setTab] = useState('AI & models')
  const categories = [{ name: 'AI & models', icon: Cpu }, { name: 'Appearance', icon: Palette }, { name: 'Permissions', icon: ShieldCheck }]
  return <Dialog title="Settings" onClose={() => app.setSettingsOpen(false)} className="settings-dialog"><div className="dialog-head"><div><span className="eyebrow">ALTREX CODE</span><h2>Settings</h2></div><IconButton label="Close settings" onClick={() => app.setSettingsOpen(false)}><X size={17} /></IconButton></div><div className="settings-layout"><nav aria-label="Settings categories">{categories.map(({ name, icon: Icon }) => <button key={name} aria-current={tab === name ? 'page' : undefined} className={tab === name ? 'selected' : ''} onClick={() => setTab(name)}><Icon size={16} />{name}</button>)}</nav><div className="settings-content">
    <h3>{tab}</h3>
    {tab === 'AI & models' && app.projectRuns.length > 0 && <details><summary>Project runs · {app.projectRuns.length}</summary>{app.projectRuns.map(run => <MultiAiRun key={run.id} run={run} onRestart={() => app.restartRun(run)} busy={!!app.activeRequestId} />)}</details>}
    {tab === 'AI & models' && <>
      <div className="setting-row"><div><strong>AI Providers</strong><p>{app.providerStatus.profiles?.length ? `${app.providerStatus.profiles.length} securely saved provider${app.providerStatus.profiles.length === 1 ? '' : 's'} · ${app.providerStatus.profiles.filter(profile => profile.connectionState === 'CONNECTED').length} ready` : 'Connect a cloud provider or detect local Ollama'}</p></div><div className="dialog-actions"><button className="secondary-button" disabled={!!app.activeRequestId || app.testingProvider} onClick={() => void app.refreshProviderModels()}>Refresh models</button><button className="secondary-button" disabled={!!app.activeRequestId} onClick={() => { app.setSettingsOpen(false); app.setConnectOpen(true) }}>Manage providers</button></div></div>
      {app.providerStatus.profiles?.map(profile => <div className="setting-row" key={`${profile.providerId}:${profile.baseUrl}`}><div><strong>{profile.displayName}</strong><p>{profile.model || 'No model selected'}</p><small>{profile.modelsDiscovered} models discovered · {profile.toolCompatibleModels} verified for tools{profile.lastErrorCategory ? ` · ${profile.lastErrorCategory}` : ''}</small></div><span className="metadata">{profile.connectionState.replaceAll('_', ' ')}</span></div>)}
      {!!app.providerDiagnostics.length && <details><summary>Advanced request diagnostics · {app.providerDiagnostics.length}</summary>{app.providerDiagnostics.slice(0, 30).map(item => <div className="setting-row" key={item.id}><div><strong>{item.provider} · {item.model}</strong><p>{item.status.toUpperCase()} · {item.durationMs} ms · {item.inputTokens} input tokens · {item.retries} retries</p><small>{item.errorCategory ?? 'OK'}{item.httpStatus ? ` · HTTP ${item.httpStatus}` : ''}{item.fallbackDestination ? ` · Fallback → ${item.fallbackDestination}` : ''}{item.technicalDetails ? ` · ${item.technicalDetails}` : ''}</small></div></div>)}</details>}
      {app.providerStatus.connected && <div className="setting-row"><div><strong>Remove connection</strong><p>Remove all saved provider credentials.</p></div><button className="text-button danger" disabled={!!app.activeRequestId} onClick={() => void app.disconnectProvider()}>Disconnect all</button></div>}
      <div className="setting-row"><div><strong>Codex runtime</strong><p>{app.runtime?.codex.available ? app.runtime.codex.version : 'Not detected on this computer'}</p></div><span className="metadata">{app.runtime?.codex.available ? 'Detected' : 'Unavailable'}</span></div><p className="settings-note"><KeyRound size={15} />Provider API keys are encrypted by your operating system. They are never stored in project files.</p>
    </>}
    {tab === 'Appearance' && <><div className="setting-row"><div><strong>Theme</strong><p>Neutral charcoal with the original ALTREX marks.</p></div><span className="theme-swatch" title="Dark theme" /></div><div className="setting-row"><div><strong>Compact sidebar</strong><p>Keep navigation as a narrow icon rail.</p></div><Toggle label="Compact sidebar" checked={app.sidebarCollapsed} onChange={() => app.setSidebarCollapsed(!app.sidebarCollapsed)} /></div><div className="setting-row"><div><strong>Motion</strong><p>Follows your system’s reduced motion preference.</p></div><span className="metadata">System</span></div></>}
    {tab === 'Permissions' && <><div className="setting-row"><div><strong>Agent workspace</strong><p>{app.project?.path ?? 'No project selected'}</p></div></div><div className="setting-row"><div><strong>Ask</strong><p>Read-only answers using your supplied project context and attachments.</p></div></div><div className="setting-row"><div><strong>Agent</strong><p>Can read and edit project files, install dependencies, and run supported development commands. Codex uses workspace-write sandboxing. Connected provider commands inherit your OS permissions.</p></div></div><div className="setting-row"><div><strong>Provider access</strong><p>Prompts, selected project context and attachments are sent to the provider you connect when you submit a task.</p></div></div></>}
    </div></div><footer className="settings-footer"><AltrexLogo size={20} /><span>ALTREX CODE</span><small>{app.runtime ? `Electron ${app.runtime.electron}` : 'Renderer preview'}</small></footer></Dialog>
}

